version = 1
SPDX-PackageName = "gateway-rotator"
SPDX-PackageSupplier = "Deutsche Telekom AG <opensource@telekom.de>"
SPDX-PackageDownloadLocation = "https://github.com/telekom/gateway-rotator"

[[annotations]]
path = [".gitignore"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom AG"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["go.mod", "go.sum"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom AG"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**/*_testdata/*", "docs/**", "CHANGELOG.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom AG"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".dockerignore", ".DS_Store", "internal/*", "release.config.js", "package.json", "package-lock.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Deutsche Telekom AG"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".golangci.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2025 Marat Reymers"
SPDX-License-Identifier = "MIT"