# SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../default

images:
- name: k8s-tls-rotator
  newName: mtr.devops.telekom.de/tardis-internal/gateway/rotator
  newTag: latest

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [
        "name": "eni-pull-mtr-devops-tardis-internal-secret",
        "name": "eni-pull-mtr-devops-tardis-common-secret"
      ]
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
  target:
    kind: Deployment
