# SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: k8s-tls-rotator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
